config/routes.rb
ArcoPortfolio::Application.routes.draw do

  get 'requests' => 'requests#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  root :to => 'static_pages#index'

  resources :requests
  

end

app/models/request.rb
class Request < ActiveRecord::Base
	attr_accessible :name, :email, :website, :message

	validates :name, :message, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation

  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize

  protected

  	def authorize
  		unless User.find_by_id(session[:user_id])
  			redirect_to login_url, notice: "Please log in"
  		end
  	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  def index
  	@requests = Request.all
  end

  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  def new
  	@request = Request.new

  	respond_to do |format|
  		format.html
  		format.json { render json: @request }
  	end
  end

  def create
  	@request = Request.new(params[:request])

  	respond_to do |format|
  		if @request.save
  			format.html { redirect_to '/#contact', notice: "Message was sent successfully!"}
  			format.json { render json: @request, status: :created, location: @request }
  		else
  			format.html { redirect_to '/#contact', notice: "Failed to fill all required fields, please try again."}
  			format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
  	end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize	

  def new
  end

  def create
  	user = User.find_by_name(params[:name])
  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to requests_url
  	else
  		redirect_to login_url, alert: "Invalid user/password combination"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authorize	

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url notice: "User #{@user.name} was successfully created."}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to redirect_to users_url notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArcoPortfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag 'logo.png' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<div class="row">
<% if notice %>
	<p id="notice"><%= notice %></p>
	<% end %>

	<%= form_for :request, :url => {:action => :create, :controller => :requests} do |f| %>

	<div class="col-md-6">
		<%= f.text_area :message, :placeholder => 'Start your message here...' %>
	</div>

	<div class="col-md-6">
			<%= f.text_field :name, :placeholder => 'Your Name (required)' %>

			<%= f.text_field :email, :placeholder => 'Your Email (required)' %>
	
			<%= f.text_field :website, :placeholder => 'Your Website' %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="contact-button general_bg">
		<i class="icon-envelope"></i>
		<%= f.submit "" %>
		<% end %>
		</div>
	</div>
</div>

app/views/requests/index.html.erb
<center>
<h1 class="request_list">All Requests</h1>

<table class="table">
  <tr>
  	<th class="request">Message</th>
    <th class="request">Name</th>
    <th class="request">Email</th>
    <th class="request">Website</th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td class="request message"><%= request.message %></td>
    <td class="request"><%= request.name %></td>
    <td class="request"><%= request.email %></td>
    <td class="request"><%= request.website %></td>
  </tr>
<% end %>
</table>
</center>

app/views/static_pages/index.html.erb
<header id="home" class="home_parallax slide-menu">
	<div class="home_text">
		<div class="hello">
			<%= image_tag 'line.png', :class => 'line-decorative' %>
			<span>Welcome to</span>
			<%= image_tag 'line.png', :class => 'line-decorative' %>
		</div>
		<div class="home_text_Q">
			<p class="home_page_title">ARCO WEB DEV</p>
		</div>
		<div class="home_text_W">
			<p>Tailored Web Solutions</p>
		</div>
		<div class="home_bottom_arrow">
			<a href="#about"><i class="icon-angle-down icon-3x"></i></a>
		</div>
	</div>
</header>
		<!-- MAIN MENU -->
		<nav id="main_menu" class="general_bg sticky-menu general_color">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="container_logo">
							<div class="logo">
								<%= link_to (image_tag('arco_logo.png')), root_path %>
							</div>
						</div>
						<div class="container_menu visible-md visible-lg" id="desktop-menu">
							<ul id="nav" class="menu scrolling-links">
								<li><a href="#home">Home</a></li>                
								<li><a href="#about">About</a></li>
								<li><a href="#services">Services</a></li>
								<li><a href="#portfolio">Portfolio</a></li>
								<li><a href="#contact">Contact</a></li>
								<% if session[:user_id] %>

								<li><%= link_to 'Logout',   logout_path, method: :delete %></li>
								<li><%= link_to 'Requests', requests_path %></li>

								<% end %>
							</ul>
						</div>
						<div class="container_menu hidden-md hidden-lg">
							<div class="menu-mobile-button general_color">
								<i class="icon-reorder"></i>
							</div>
						</div>
						<div class="clearfix"></div>			
					</div>
				</div>
			</div>
			<!-- MOBILE MENU -->
			<div class="scrolling-links hidden-md hidden-lg">
				<div id="mobile-menu">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul>
									<li><a href="#home">Home</a></li>                
									<li><a href="#about">About</a></li>
									<li><a href="#services">Services</a></li>
									<li><a href="#portfolio">Portfolio</a></li>
									<li><a href="#contact">Contact</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</nav>
		<!-- ABOUT SECTION -->
		<div id="about" class="slide-menu">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="title">
							<h2></span>About Us</h2>
							<div class="head-line"></div>
						</div>
						<div class="text_Q">What we <span class="general_color">Do</span></div>

						<div class="text_W what_we_do"><span class="general_color">Full stackweb development,</span>  project consulting, and e-commerce solutions. Our experienced team utilizes new technologies and a true understanding of the marketplace to build products customized to <span class="general_color">your needs.</span>

					</div>
				</div>
			</div>
			
		</div>
		<div class="content_box_parallax">
			<div class="container">
				<div class="row">
					<div class="col-md-3 info-box">
						<%= image_tag 'rails.png' %>
						<h3>Ruby on Rails</h3>
						<p>Sturdy back end infrastructure, optimized for sustainable programming productivity.</p>
					</div>
					<div class="col-md-3 info-box">
						<%= image_tag 'html5.png' %>
						<h3>HTML 5</h3>
						<p>The necessary basics of web design.</p>
					</div>
					<div class="col-md-3 info-box">
						<%= image_tag 'css3.png' %>
						<h3>CSS 3</h3>
						<p>Front end services that utilize SCSS and the Bootsrap framework to provide clean, innovative design for your project.</p>
					</div>
					<div class="col-md-3 info-box">
						<%= image_tag 'jquery.png' %>
						<h3>jQuery</h3>
						<p>Sleek, flowing animations that combine to create a natural and intuitive experience for the end user.</p>
					</div>
				</div>
			</div>
		</div>
			<!-- TEAM -->
			<div id="team" class="team_parallax clearfix">
				<div class="title">
						<h2 class="team-label">Meet The Team</h2>
						<div class="head-line"></div>
				</div>
				<div class="container team-container">
					<div class="row">
						<div class="col-md-3 team-member">
							<div class="team-social">
								<div class="team-icons">	
									<a href="http://www.linkedin.com/pub/travis-brault/58/2a0/159/" class="linkedin-bg social-icon"><i class="icon-linkedin"></i></a>
									<a href="https://github.com/travisbrault" class="github-bg social-icon"><i class="icon-github"></i></a>
								</div>
								<%= image_tag 'trav1.png', :class => 'img-circle' %>
								<div class="team-button"><i class="icon-user"></i></div>
							</div>
							<h3 class="team-members">Travis Brault</h3>
							<p class="team-work">Web Developer</p>
						</div>
						<div class="col-md-3 team-member">
							<div class="team-social">
								<div class="team-icons">
									<a href="http://www.linkedin.com/pub/van-michael-nguyen/1b/217/3b3/" class="linkedin-bg social-icon"><i class="icon-linkedin"></i></a>
									<a href="https://github.com/vanmichael" class="github-bg social-icon"><i class="icon-github"></i></a>
								</div>
								<%= image_tag 'van.png', :class => 'img-circle' %>
								<div class="team-button"><i class="icon-user"></i></div>
							</div>
							<h3 class="team-members">Van Nguyen</h3>
							<p class="team-work">Web Developer</p>
						</div>
					</div>
				</div>
			</div>
			
		</div>
		<!-- SERVICES -->
		<div id="services" class="slide-menu">
			<div class="container">	
					<div class="title title-style-1">
						<h2>Services</h2>
						<div class="head-line-white"></div>
					</div>
						<div class="row clearfix">
							<div class="col-md-3 services-box">
								
								<h4><i class="icon-info services-icons"></i> Informational Sites</h4>
								<p>
									Need to get your name out there? We build custom portfolios, resume pages, and online menus -- providing brick-and-mortar shops exposure to the online world.
								</p>
							</div>
							<div class="col-md-3 services-box">
								
								<h4><i class="icon-shopping-cart services-icons"></i> E-Commerce/Shopify</h4>
								<p>
									We build custom e-commerce websites to provide your business access to the online marketplace. If you'd rather use Shopify, we can do that too!
								</p>
							</div>
							<div class="col-md-3 services-box">
								
								<h4><i class="icon-youtube-play services-icons"></i> Web Apps</h4>
								<p>
									We build solid web applications, combining front-end beauty with robust back-end services.
								</p>
							</div>
							<div class="col-md-3 services-box">
								
								<h4><i class="icon-briefcase services-icons"></i> Contract Work</h4>
								<p>
									Already have a website built on rails and need a feature added, or a couple of things improved? We can help with that.
								</p>
							</div>
						</div>
			</div>
		</div>
		<!-- PRICING TABLES -->
		<!-- PORTFOLIO -->
		<div id="portfolio" class="slide-menu clients_parallax">
			<div class="container">
				<div class="title title-style-1">
					<h2>Portfolio</h2>
					<div class="head-line-white"></div>
				</div>
				<h2 class="clients-text">Below are clients that have trusted us</h2>
					<ul class="client-carousel">
						<li class="client_image milestone"><%= link_to (image_tag('milestone.png')), 'http://www.milestonerecovery.com', :class => 'img-responsive milestone-text' %></li>
						<li class="client_image babsonmexico"><%= link_to (image_tag('babsonmexico.png')), 'http://www.babsonmexico.com', :class => 'img-responsive babsonmexico-text' %></li>
						<li class="client_image globalcatalysts"><%= link_to (image_tag('globalcatalysts.png')), 'http://www.globalcatalysts.com.mx', :class => 'img-responsive globalcatalysts-text' %></li>
						<li class="client_image rvn"><%= link_to (image_tag('rvn.png')), 'http://www.rvnnyc.com', :class => 'img-responsive rvn-text' %></li>
					</ul>
			</div>
		</div>

		<!-- TESTIMONIALS -->
		<!-- NEWS -->
		<!-- TWITTER -->
		<!-- CONTACT -->
		<div id="contact" class="slide-menu">
			<div class="container">
				<div class="title title-style-2">
					<h2>Contact</h2>
					<div class="head-line"></div>
				</div>
				<h2 class="contact-text">Propose a project, request a <span class="general_color">quote,</span> or just call to chat.</h2>
				<div class="contact-info">
					<div class="col-md-4">
						<div class="style-icon-1 general_bg">
							<i class="icon-map-marker"></i>
						</div>
						<div class="contact-text-info">
							195 Binney Street,
							Cambridge, MA
						</div>
					</div>
					<div class="col-md-4">
						<div class="style-icon-1 general_bg">
							<i class="icon-phone"></i>
						</div>
						<div class="contact-text-info">
							(978) 602-7171
						</div>
					</div>
					<div class="col-md-4">
						<div class="style-icon-1 general_bg">
							<i class="icon-envelope-alt"></i>
						</div>
						<div class="contact-text-info">
							arcowebdev@gmail.com
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="contact-form">
					<%= render 'requests/form' %>
				</div>
				<div class="contact-success">
					<h2 class="contact-text">Thank you for your <span class="general_color">message</span>. We will try to answer as soon as possible</h2>
				</div>
			</div>
		</div>
		<!-- GOOGLE MAP -->
		<div id="google-map">
			<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=195%2Bbinney%2Bstreet%2C%2Bcambridge%2C%2Bma%2B02142&ie=UTF8&z=12&t=m&iwloc=near&output=embed"></iframe>
		</div>
		<div id="backtop">
			<i class="icon-angle-up"></i>
		</div>
		<!-- FOOTER -->
		<footer id="footer" class="general_bg">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<p class="copyright">2013 - Arco Web Development</p>
					</div>
					<div class="col-md-6 foot-social">
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</footer>

app/views/users/_form.html.erb
<div class="user_form">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="center">
    <legend>Enter User Details</legend>

      <div>
        <%= f.label :name %><br />
        <%= f.text_field :name, size: 40 %>
      </div>
      <div>
        <%= f.label :password, 'Password' %><br />
        <%= f.password_field :password, size: 40 %>
      </div>
       <div>
        <%= f.label :password_confirmation, 'Confirm' %><br />
        <%= f.password_field :password_confirmation, size: 40 %>
      </div>
      <div>
        <%= f.submit %>
      </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>